### ISSUE TITLE
Doesn't work after latest pull

### ISSUE THREAD

**Issue by Slug-Cat** [ClayShoaf/oobabooga-one-click-bandaid#2]
The implementation on ooba changed recently as detailed here: https://github.com/oobabooga/text-generation-webui/issues/584
Using the bandaid no longer functions as expected, delivering the error specified in the Oobabooga issue.

**Comment by 8WSR0hX** [comment]
Try this one. https://github.com/ClayShoaf/oobabooga-one-click-bandaid/pull/3/commits/313ae1c3abc4bfb62786c2bd23212abdd69b909f from https://github.com/ClayShoaf/oobabooga-one-click-bandaid/pull/3

**Comment by ClayShoaf** [comment]
I'm not gonna be able to work on this for about a week. I would check the link at the top of the readme. It seems like that person will probably be staying more up to date than me. Sorry about that.

**Comment by ClayShoaf** [comment]
> Try this one. [313ae1c](https://github.com/ClayShoaf/oobabooga-one-click-bandaid/commit/313ae1c3abc4bfb62786c2bd23212abdd69b909f) from #3

@Slug-Cat, can you try this change and see if it works? If it does, I'll merge it. I can't test right now

**Comment by Slug-Cat** [comment]
> 

I ran that one, but now I get this error. Very odd, as torch worked fine before the latest pull and my attempts to fix it.
```
Traceback (most recent call last):
  File "E:\oobabooga\text-generation-webui\server.py", line 234, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "E:\oobabooga\text-generation-webui\modules\models.py", line 101, in load_model
    model = load_quantized(model_name)
  File "E:\oobabooga\text-generation-webui\modules\GPTQ_loader.py", line 92, in load_quantized
    model = accelerate.dispatch_model(model, device_map=device_map, offload_buffers=True)
  File "E:\oobabooga\installer_files\env\lib\site-packages\accelerate\big_modeling.py", line 370, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "E:\oobabooga\installer_files\env\lib\site-packages\accelerate\hooks.py", line 471, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "E:\oobabooga\installer_files\env\lib\site-packages\accelerate\hooks.py", line 155, in add_hook_to_module
    module = hook.init_hook(module)
  File "E:\oobabooga\installer_files\env\lib\site-packages\accelerate\hooks.py", line 244, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "E:\oobabooga\installer_files\env\lib\site-packages\accelerate\utils\modeling.py", line 147, in set_module_tensor_to_device
    new_value = old_value.to(device)
  File "E:\oobabooga\installer_files\env\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Press any key to continue . . .
```

**Comment by ClayShoaf** [comment]
Did you do that from a fresh download?

**Comment by Slug-Cat** [comment]
> Did you do that from a fresh download?

No, an existing installation. I'm going to try deleting my venv and applying a fix that worked previously with torch not detecting cuda to see if that works.

**Comment by ClayShoaf** [comment]
I would try it with a brand new download, but if you're still stuck, I would try this one: https://github.com/jllllll/one-click-installers
Sorry I can't be of more help. I kind of made this on the fly for that particular commit.

**Comment by Slug-Cat** [comment]
I'll try a fresh install

**Comment by ClayShoaf** [comment]
alright. I'll be awake for another couple of hours. If it works for you, I'll change it.

**Comment by Slug-Cat** [comment]
It appears to work so far after a fresh install, and applying the same fix I had to when I originally installed the ooba UI, here:
https://github.com/oobabooga/text-generation-webui/issues/15#issuecomment-1404001472
Basically just removing plain torch from the install instructions, only leaving the cuda version. For some reason leaving the normal one makes it ignore the cuda version on my system.

Yep, it works. However, for some reason I'm getting 7 tokens per second with the new implementation/model rather than ~11. A problem for another time. 
![image](https://user-images.githubusercontent.com/53411759/227818282-d415d3e5-9dfd-4316-8c5b-0b6477d89429.png)

**Comment by ClayShoaf** [comment]
Did you remove the `git reset --hard 468c47c01b4fe370616747b6d69a2d3f48bab5e4` line as @8WSR0hX suggested?

**Comment by Slug-Cat** [comment]
I used the one-click installer from jllllll

**Comment by ClayShoaf** [comment]
@jllllll
